# Generated by Django 3.2.3 on 2021-07-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wechat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('CreateTime', models.DateTimeField(verbose_name='关注时间')),
                ('FromUserName', models.CharField(max_length=30, verbose_name='粉丝')),
                ('ToUserName', models.CharField(max_length=30, verbose_name='公众号')),
                ('state', models.IntegerField(choices=[('0', '取关中'), ('1', '关注中')], verbose_name='状态')),
            ],
            options={
                'verbose_name': '公众号粉丝',
                'verbose_name_plural': '公众号粉丝',
                'db_table': 'wechat_fans',
            },
        ),
    ]
