# Generated by Django 3.2.3 on 2021-07-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_alter_wechat_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechat',
            name='CreateTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='关注时间/取关时间'),
        ),
    ]
