# Generated by Django 3.2.3 on 2021-07-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_alter_wechat_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechat',
            name='state',
            field=models.IntegerField(choices=[('0', '关注中'), ('1', '取关中')], verbose_name='状态'),
        ),
    ]
