# Generated by Django 3.2.3 on 2021-07-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_alter_wechat_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatWeb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('CreateTime', models.DateTimeField(auto_now=True, null=True, verbose_name='授权时间')),
                ('openid', models.CharField(blank=True, max_length=300, null=True, verbose_name='用户唯一标识')),
                ('nickname', models.CharField(blank=True, max_length=300, null=True, verbose_name='用户昵称')),
                ('sex', models.IntegerField(choices=[('0', '未知'), ('1', '男性'), ('2', '女性')], verbose_name='性别')),
                ('language', models.CharField(blank=True, max_length=300, null=True, verbose_name='语言')),
                ('city', models.CharField(blank=True, max_length=300, null=True, verbose_name='城市')),
                ('province', models.CharField(blank=True, max_length=300, null=True, verbose_name='省份')),
                ('country', models.CharField(blank=True, max_length=300, null=True, verbose_name='国家')),
                ('headimgurl', models.CharField(blank=True, max_length=500, null=True, verbose_name='头像')),
                ('privilege', models.CharField(blank=True, max_length=300, null=True, verbose_name='用户特权信息')),
            ],
            options={
                'verbose_name': '网页授权的用户',
                'verbose_name_plural': '网页授权的用户',
                'db_table': 'web_authorization_user',
            },
        ),
    ]
